name: CI - Gestión de Secrets

on:
  push:
    branches:
      - feature/seminario/secrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Instalar Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: '1.36.0'
        kubernetes-version: '1.28.3'

    - name: Mostrar estado del clúster
      run: kubectl get nodes

    - name: Build imagen Docker
      run: |
        docker build -t python-flask:latest .

    - name: Aplicar manifiestos (incluyendo secretos)
      run: |
        kubectl apply -f manifests/

    - name: Verificar secretos
      run: |
        kubectl get secrets app-secret -o yaml
