name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Traemos el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Instalar python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Construcción de imagen con Dockerfile
      - name: Build Docker image
        run: docker build -t app-manifests:latest .

      # 4) instalar kubeconform
      - name: Instalar kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | 
          tar xz sudo mv kubeconform /usr/local/bin/
      
      # 5) Linting con kubeconform
      - name: Linter para los manifiestos
        run: |
          kubeconform manifests/deployment.yaml
          kubeconform manifests/service.yaml
      
      # 6)  Valida manifiestos
      - name: Validacion de manifests con kubectl dry-run
        run: |
          kubectl apply --dry-run=client -f manifests/deployment.yaml
          kubectl apply --dry-run=client -f manifests/service.yaml
